spring:
  main:
    allow-bean-definition-overriding: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/feed}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    port: ${REDIS_PORT:6379}
    host: ${REDIS_HOST:localhost}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            protocols: TLSv1.3
          starttls:
            enable: true
            required: true

    auth-exp: ${AUTH-CODE-EXP}

cloud:
  aws:
    credentials:
      access_key: ${S3_ACCESS_KEY:asdf}
      secret_key: ${S3_SECRET_KEY:asdf}
    s3:
      bucket: ${S3_BUCKET:feed}
    region:
      static: ${S3_REGION:ap-northeast-2}
    stack:
      auto: false


jwt:
  secret_key: ${SECRET_KEY}
  access_exp: ${ACCESS_EXP}
  refresh_exp: ${REFRESH_EXP}
  header: ${HEADER}
  prefix: ${PREFIX}

fcm:
  path: ${FCM_PATH}