spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    port: ${REDIS_PORT}
    host: ${REDIS_HOST}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL-USERNAME}
    password: ${EMAIL-PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            protocols: TLSv1.3
          starttls:
            enable: true
            required: true

    auth-exp: ${AUTH-CODE-EXP}

cloud:
  aws:
    credentials:
      access_key: ${S3_ACCESS_KEY}
      secret_key: ${S3_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ${S3_REGION}
    stack:
      auto: false

servlet:
  multipart:
    max-file-size: 5MB
    max-request-size: 5MB
jwt:
  secret_key: ${SECRET_KEY}
  access_exp: ${ACCESS_EXP}
  refresh_exp: ${REFRESH_EXP}
  header: ${HEADER}
  prefix: ${PREFIX}